/* FILE: exchange_dmi_cn_12ngbrs.h
 *
 * Exchange and Dzyaloshinskii-Moriya field and energy calculation.
 *
 * DMI is defined for the Cn crystallographic class [1, 2]:
 *
 * $w_\text{dmi} = D1 ( L_{xz}^{(x)} + L_{yz}^{(y)} ) + D2 ( L_{xz}^{(y)} + L_{zy}^{(x)} )
 *
 * Note that this has the opposite sign than in [3].
 *
 * This extension works both with and without periodic boundary conditions.
 *
 * Extension and modification by David Cortes-Ortuno based on the
 * oommf-extension-dmi-cnv class by the joommf project
 *
 * [1] A. N. Bogdanov and D. A. Yablonskii. Zh. Eksp. Teor. Fiz. 95, 178-182 (1989).
 * [2] C. Abert. Micromagnetics and spintronics: models and numerical methods.
 *     The European Physical Journal B. 92 (120). 2019.
 * [3] Ado et al. PRB 101, 161403(R) (2020)
 */

#ifndef _OXS_EXCHDMI_CN_12NGBRS
#define _OXS_EXCHDMI_CN_12NGBRS

#include "atlas.h"
#include "energy.h"
#include "key.h"
#include "mesh.h"
#include "meshvalue.h"
#include "rectangularmesh.h"
#include "simstate.h"
#include "threevector.h"
#include "mesh_neighbors.h"  // This include <vector>

/* End includes */

class Oxs_ExchangeAndDMI_Cn_12ngbrs : public Oxs_Energy {
private:
  OC_INT4m A_size;
  OC_REAL8m D1;
  OC_REAL8m D2;
  OC_REAL8m Aex;
  Oxs_Key<Oxs_Atlas> atlaskey;
  Oxs_OwnedPointer<Oxs_Atlas> atlas;
  mutable OC_INT4m mesh_id;
  mutable Oxs_MeshValue<OC_INT4m> region_id;

  // Periodic boundaries?
  mutable int xperiodic;
  mutable int yperiodic;
  mutable int zperiodic;

  mutable int xdim;
  mutable int ydim;
  mutable int zdim;
  mutable OC_REAL8m wgtx;
  mutable OC_REAL8m wgty;
  mutable OC_REAL8m wgtz;
  mutable OC_REAL8m deltaX;
  mutable OC_REAL8m deltaY;
  mutable OC_REAL8m deltaZ;
  mutable OC_INDEX xydim;
  mutable OC_INDEX xyzdim;

  // Array with neighbors. Size should be: 6 * mesh size
  std::vector<OC_INDEX> n_neighbors;
  std::vector<OC_INDEX> nn_neighbors;

protected:
  virtual void GetEnergy(const Oxs_SimState &state, Oxs_EnergyData &oed) const;

public:
  virtual const char *ClassName() const; // ClassName() is
  /// automatically generated by the OXS_EXT_REGISTER macro.
  Oxs_ExchangeAndDMI_Cn_12ngbrs(const char *name,     // Child instance id
                    Oxs_Director *newdtr, // App director
                    const char *argstr);  // MIF input block parameters
  virtual ~Oxs_ExchangeAndDMI_Cn_12ngbrs();
  virtual OC_BOOL Init();
};

#endif // _OXS_EXCHDMI_CN_12NGBRS
