/* FILE: xpint.h                    -*-Mode: c++-*-
 *
 * The OOMMF eXtra Precision extension internal header file.
 *
 * NOTICE: Please see the file ../../LICENSE
 *
 * Files inside pkg/xp may include this file as needed.  No
 * file inside pkg/xp should include the public header xp.h,
 * lest false circular dependencies errors are generated by
 * pimake CSourceFile Dependency calls.
 *
 */

#ifndef _XPINT
#define _XPINT

#include "oc.h"

#include "version.h"
#define XP_VERSION OC_MAKE_VERSION(XP)

// Declarations of classes in this extension

#include "xpport.h"  // Needed for XP_USE_ALT_DOUBLEDOUBLE defn

#if XP_USE_ALT_DOUBLEDOUBLE == 0
# include "doubledouble.h"
#else
# include "alt_doubledouble.h"
#endif

/* End includes */     // Optional directive to pimake

// Prototypes for the routines defined in xp.cc
Tcl_PackageInitProc Xp_Init;

#endif /* _XPINT */
