/* FILE: DMI_D2d.cc            -*-Mode: c++-*-
 *
 * Dzyaloshinsky-Moriya class for materials with D_2d crystallographic
 * symmetry [1]:
 *
 *      w_D = D ( L_{zx}^{(y)} + L_{zy}^{(x)} )
 *
 * Modification from Oxs_exchange6ngbr [2] by 
 * V. Nehruji[*], D. Cortes[+], H. Fangohr[+,o], P. Hatton[*]
 *
 * Working with Periodic Boundaries.
 *
 * [*] Department of Physics, University of Durham
 * [+] University of Southampton
 * [o] European XFEL GmbH
 *
 * [1] A. N. Bogdanov and D. A. Yablonskii. Zh. Eksp. Teor. Fiz. 95, 178-182 (1989).
 * [2] Rohart, S., & Thiaville, A. Physical Review B, 88, 184422 (2013).
 *
 */

#ifndef _OXS_DMI_D2D
#define _OXS_DMI_D2D

#include "atlas.h"
#include "key.h"
#include "energy.h"
#include "mesh.h"
#include "meshvalue.h"
#include "simstate.h"
#include "threevector.h"
#include "rectangularmesh.h"

/* End includes */

class Oxs_DMI_D2d:public Oxs_Energy {
private:
  OC_INT4m A_size;
  OC_REAL8m** D;
  Oxs_Key<Oxs_Atlas> atlaskey;  
  Oxs_OwnedPointer<Oxs_Atlas> atlas;
  mutable OC_INT4m mesh_id;
  mutable Oxs_MeshValue<OC_INT4m> region_id;

  // Periodic boundaries?
  mutable int xperiodic;
  mutable int yperiodic;
  mutable int zperiodic;

protected:
  virtual void GetEnergy(const Oxs_SimState& state,
			 Oxs_EnergyData& oed) const;

public:
  virtual const char* ClassName() const; // ClassName() is
  /// automatically generated by the OXS_EXT_REGISTER macro.
  Oxs_DMI_D2d(const char* name,     // Child instance id
		    Oxs_Director* newdtr, // App director
		    const char* argstr);  // MIF input block parameters
  virtual ~Oxs_DMI_D2d();
  virtual OC_BOOL Init();
};


#endif // _OXS_DMI_D2D
