# Build OOMMF in Debian container
# see ../../Makefile for details

name: in-docker

on:
  push:
  schedule:
    - cron: '0 0 2 * *'  # run once per month

jobs:
  in-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2
      
    - name: Build and test inside container
      run: make in-docker
