name: on-macos

on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  on-ubuntu-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/workflows/environment.yml

    - name: Build OOMMF
      run: make build-with-all

    - name: Set OOMMFTCL
      run: echo "OOMMFTCL=$GITHUB_WORKSPACE/oommf/oommf.tcl" >> $GITHUB_ENV

    - name: Test OOMMF
      run: make test-all
