name: ubermag-container

on:
  push:
  schedule:
    - cron: '0 0 2 * *'  # run once per month
  workflow_dispatch:


jobs:
  on-ubuntu-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Initialisation
      uses: actions/checkout@v3

    - name: Build OOMMF in Container from master branch
      run: cd docker && make build

    - name: Run stdproblem 3
      run: cd docker && make test

