name: workflow

on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y tk-dev tcl-dev
      
    - name: Build OOMMF
      run: make build-with-all

    - name: Test stdprob3
      run: tclsh oommf/oommf.tcl boxsi +fg oommf/app/oxs/examples/stdprob3.mif -exitondone 1
      
    - name: Test stdprob4
      run: tclsh oommf/oommf.tcl boxsi +fg oommf/app/oxs/examples/stdprob4.mif -exitondone 1
    